"""empty message

Revision ID: 84b78254f562
Revises: None
Create Date: 2017-05-26 09:44:43.092952

"""

# revision identifiers, used by Alembic.
revision = '84b78254f562'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_modified', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('date_modified', sa.Date(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['bucket_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('bucket_list')
    # ### end Alembic commands ###
